version: '2'

networks:
  test:

services:

  ca_pengusaha:
    image: hyperledger/fabric-ca:1.5.6
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.pengusaha.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_CA_REENROLLIGNORECERTEXPIRY=true
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/pengusaha:/etc/hyperledger/fabric-ca-server
    container_name: ca.pengusaha.example.com
    hostname: ca.pengusaha.example.com
    networks:
      - test

  ca_bpjh:
    image: hyperledger/fabric-ca:1.5.6
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.bpjh.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_SERVER_CA_REENROLLIGNORECERTEXPIRY=true
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/bpjh:/etc/hyperledger/fabric-ca-server
    container_name: ca.bpjh.example.com
    hostname: ca.bpjh.example.com
    networks:
      - test

  ca_lph:
    image: hyperledger/fabric-ca:1.5.6
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.lph.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=10054
      - FABRIC_CA_SERVER_CA_REENROLLIGNORECERTEXPIRY=true
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/lph:/etc/hyperledger/fabric-ca-server
    container_name: ca.lph.example.com
    hostname: ca.lph.example.com
    networks:
      - test

  ca_orderer:
    image: hyperledger/fabric-ca:1.5.6
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
      - FABRIC_CA_SERVER_CA_REENROLLIGNORECERTEXPIRY=true
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer
    networks:
      - test
